name: auto-pr

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    uses: guilhermelinosp/templates/.github/workflows/auto-pr.yml@af2bcbe5d72882b5ab9145a02620d229dd14587f # main
